# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsToScrape',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('brand', models.IntegerField(default=0)),
                ('catalog_number', models.CharField(default=None, max_length=25, null=True)),
                ('web_price', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Items To Scrape',
                'verbose_name_plural': 'Items To Scrape (visible)',
            },
        ),
        migrations.CreateModel(
            name='ScrapedItems',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(default=None, max_length=128, null=True)),
                ('scrape_date_time', models.DateTimeField(auto_now_add=True)),
                ('suggested', models.CharField(default=None, max_length=25, null=True)),
                ('list_price', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('wholesale_price', models.FloatField(default=0.0)),
                ('image_small', models.CharField(default=None, max_length=25, null=True)),
                ('image_large', models.CharField(default=None, max_length=25, null=True)),
                ('title', models.CharField(default=None, max_length=256, null=True)),
                ('category_discount', models.FloatField(default=0.0)),
                ('its', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape_items.ItemsToScrape')),
            ],
            options={
                'verbose_name': 'Scraped Items',
                'verbose_name_plural': 'Scraped Items (visible)',
            },
        ),
    ]
