# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeditems',
            name='iid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeditems',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
